# Generated by Django 4.1.2 on 2022-10-13 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concierge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_name', models.CharField(max_length=70, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('phone', models.CharField(max_length=11, verbose_name='Telefone de contato')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Concierge',
                'verbose_name_plural': 'Concierges',
                'db_table': 'concierge',
            },
        ),
    ]
