# Generated by Django 4.1.2 on 2022-10-13 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concierges', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concierge',
            options={'verbose_name': 'Porteiro', 'verbose_name_plural': 'Porteiros'},
        ),
        migrations.AlterModelTable(
            name='concierge',
            table='porteiro',
        ),
    ]
