# Generated by Django 4.1.2 on 2022-10-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_visitor_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='autorization_time',
            new_name='authorization_time',
        ),
    ]
