# Generated by Django 4.1.2 on 2022-10-15 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concierges', '0002_alter_concierge_options_alter_concierge_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_name', models.CharField(max_length=194, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('house_number', models.PositiveSmallIntegerField(verbose_name='Número da casa a ser visitado')),
                ('vehicle_plate', models.CharField(blank=True, max_length=7, null=True, verbose_name='Placa de veiculo')),
                ('arrival_time', models.DateTimeField(auto_now_add=True, verbose_name='Horário de chegada')),
                ('departure_time', models.DateTimeField(blank=True, null=True, verbose_name='Horário de saída')),
                ('autorization_time', models.DateTimeField(blank=True, null=True, verbose_name='Horário de autorização de entrada')),
                ('resident_who_authorized', models.CharField(blank=True, max_length=194, verbose_name='Morador responsável pela entrada do visitante')),
                ('concierge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='concierges.concierge', verbose_name='Porteiro que registrou')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
                'db_table': 'visitante',
            },
        ),
    ]
